blueprint:
  name: Motion, Light, and Fan Control with Humidity Threshold
  description: >
    # 🚿 Bathroom Humidity Exhaust Fan
    
    **Version: 0.1.4**
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - motion
          multiple: false
    door_sensor:
      name: Door Sensor
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - door
          multiple: false
    humidity_sensor:
      name: Humidity Sensor
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - humidity
          multiple: false
    light_entity:
      name: Smart Light
      selector:
        entity:
          domain:
          - light
          multiple: false
    fan_entity:
      name: Smart Exhaust Fan
      selector:
        entity:
          domain:
          - switch
          multiple: false
    humidity_threshold:
      name: Humidity Threshold
      description: Humidity level to act upon.
      default: 60
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: '%'
          mode: slider
          step: 1.0
    delay_timer:
      name: Delay Timer
      description: Delay before turning off devices (in seconds).
      default: 60
      selector:
        number:
          min: 1.0
          max: 300.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    max_fan_runtime:
      name: Maximum Fan Runtime
      description: "The maximum amount of time (in minutes) the fan should run before automatically turning off, regardless of humidity."
      default: 30

  source_url: https://raw.githubusercontent.com/carlosCastro99/bathBlueprint/main/motion_light_fan_humidity_control.yaml
trigger:
- platform: state
  entity_id: !input door_sensor
  to: 'off'
- platform: state
  entity_id: !input motion_sensor
  from: 'off'
  to: 'on'
#- platform:  numeric_state
#  entity_id: !input humidity_sensor
#  above: input_number.humidity_threshold
- platform: state
  entity_id: binary_sensor.status_wc_piso1_high_humidity
condition: []
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input motion_sensor
      state: 'on'
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light_entity
#humidity ON + DOOR Closed + Motion on = Light ON
  - conditions:
    - condition: state
      entity_id: binary_sensor.status_wc_piso1_high_humidity
      state: 'on'  
    - condition: state
      entity_id: !input door_sensor
      state: 'off'
    - condition: state
      entity_id: !input motion_sensor
      state: 'on'
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light_entity
    - service: switch.turn_on
      target:
        entity_id: !input fan_entity
#humidity ON + DOOR Open + Motion on = Light ON + Fan ON
  - conditions:
    - condition: state
      entity_id: binary_sensor.status_wc_piso1_high_humidity
      state: 'on'  
    - condition: state
      entity_id: !input door_sensor
      state: 'on'
    - condition: state
      entity_id: !input motion_sensor
      state: 'on'
    sequence:
    - service: light.turn_on
      target:
        entity_id: !input light_entity
    - service: switch.turn_on
      target:
        entity_id: !input fan_entity        
#humidity OFF + DOOR OPEN + Motion off = Light off  + FAN Off      
  - conditions:
    - condition: state
      entity_id: binary_sensor.status_wc_piso1_high_humidity
      state: 'off'
    - condition: state
      entity_id: !input door_sensor
      state: 'on'
    - condition: state
      entity_id: !input motion_sensor
      state: 'off'
    sequence:
    - service: light.turn_off
      target:
        entity_id: !input light_entity    
    - delay:
        hours: 0
        minutes: 0
        seconds: input_number.delay_timer
        milliseconds: 0    
    - service: switch.turn_off
      target:
        entity_id: !input fan_entity
#humidity ON + DOOR OPEN + Motion off = Light off
  - conditions:
    - condition: state
      entity_id: binary_sensor.status_wc_piso1_high_humidity
      state: 'on'
    - condition: state
      entity_id: !input door_sensor
      state: 'on'
    - condition: state
      entity_id: !input motion_sensor
      state: 'off'
      #desliga a luz apenas
    sequence:
    - service: light.turn_off
      target:
        entity_id: !input light_entity
  default:
  - delay:
      hours: 0
      minutes: !input 'max_fan_runtime'
      seconds: 0
      milliseconds: 0
  - service: fan.turn_off
    target:
      entity_id: !input fan_entity 
  - service: light.turn_off
    target:
      entity_id: !input light_entity